### ISSUE TITLE
[Error] RuntimeError: main thread is not in main loop (`self.tk.call('image', 'delete', self.name)` in `svg_brush.py`.

### ISSUE THREAD

**Issue by atljoseph** [ximinng/PyTorch-SVGRender#20]
[Error] RuntimeError: main thread is not in main loop (`self.tk.call('image', 'delete', self.name)` in `svg_brush.py`.

Installed ok, after realizing, "oh yeah, gotta activate the conda env after running the install script". :)

Generates some output, with an initial image, but not much more than that (error below).

```
$ sh script/install.sh
...
$ conda activate svgrender
...
$ python svg_render.py x=clipdraw prompt='Horse eating a cupcake'
==> system args: 
{'target': None, 'prompt': 'Horse eating a cupcake', 'neg_prompt': 'nsfw, lowres, (bad), text, error, fewer, extra, missing, worst quality, jpeg artifacts, low quality, watermark, unfinished, displeasing, oldest, early, chromatic aberration, signature, extra digits, artistic error, username, scan', 'state': {'cpu': False, 'mprec': 'no'}, 'diffuser': {'download': False, 'force_download': False, 'resume_download': False}, 'diffvg': {'print_timing': False}, 'seed': 951222, 'multirun': False, 'srange': None, 'result_path': './workspace', 'save_step': 10, 'eval_step': 10, 'mv': False, 'framefreq': 5, 'framerate': 24, 'output_dir': '/home/joseph/ai/PyTorch-SVGRender/workspace/clipdraw-2024-07-21-02-54'}
==> yaml config args: 
{'method': 'clipdraw', 'image_size': 224, 'path_svg': None, 'num_iter': 1000, 'num_stages': 1, 'lr_schedule': True, 'lr': 1, 'width_lr': 0.1, 'color_lr': 0.01, 'num_paths': 512, 'max_width': 50, 'black_stroke_color': False, 'num_aug': 4}

***** Model State *****
-> Mixed Precision: no, AMP: False
-> Weight dtype:  torch.float32
-> Working Space: '/home/joseph/ai/PyTorch-SVGRender/workspace/clipdraw-2024-07-21-02-54/sd951222-im224-P512'
Process 0 using device: cuda
-> state initialization complete 

prompt: Horse eating a cupcake
init_image shape:  torch.Size([1, 3, 224, 224])
  0%|                                                                                  | 0/1000 [00:00<?, ?it/s]/home/joseph/.local/lib/python3.10/site-packages/torchvision/transforms/functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True).
  warnings.warn(
lr: 1.000, L_train: -0.5856:   0%|                                                     | 0/1000 [00:00<?, ?it/s]Exception ignored in: <function Image.__del__ at 0x73f5307b2f80>
Traceback (most recent call last):
  File "/home/joseph/anaconda3/envs/svgrender/lib/python3.10/tkinter/__init__.py", line 4056, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x73f54f4ff7f0>
Traceback (most recent call last):
  File "/home/joseph/anaconda3/envs/svgrender/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x73f54f4ff7f0>
Traceback (most recent call last):
  File "/home/joseph/anaconda3/envs/svgrender/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x73f54f4ff7f0>
Traceback (most recent call last):
  File "/home/joseph/anaconda3/envs/svgrender/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x73f54f4ff7f0>
Traceback (most recent call last):
  File "/home/joseph/anaconda3/envs/svgrender/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Tcl_AsyncDelete: async handler deleted by the wrong thread
Aborted
```

Thanks!

**Comment by ximinng** [comment]
Sorry, I haven't had that problem.
Has anyone else experienced this problem?

**Comment by LittleTerry** [comment]
> Sorry, I haven't had that problem. Has anyone else experienced this problem?

Hi, I've got the same proble.

`(svgrender) lyxy232@lyxy232:~/lyxy/PyTorch-SVGRender$ python svg_render.py x=diffvg target='./data/fallingwater.png'

/home/lyxy232/miniconda3/envs/svgrender/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
==> system args: 
{'target': './data/fallingwater.png', 'prompt': None, 'neg_prompt': 'nsfw, lowres, (bad), text, error, fewer, extra, missing, worst quality, jpeg artifacts, low quality, watermark, unfinished, displeasing, oldest, early, chromatic aberration, signature, extra digits, artistic error, username, scan', 'state': {'cpu': False, 'mprec': 'no'}, 'diffuser': {'download': False, 'force_download': False, 'resume_download': False}, 'diffvg': {'print_timing': False}, 'seed': 951222, 'multirun': False, 'srange': None, 'result_path': './workspace', 'save_step': 10, 'eval_step': 10, 'mv': False, 'framefreq': 5, 'framerate': 24, 'output_dir': '/home/lyxy232/lyxy/PyTorch-SVGRender/workspace/diffvg-2025-01-18-00-03'}
==> yaml config args: 
{'method': 'diffvg', 'num_iter': 2000, 'lr_base': {'point': 1, 'color': 0.01, 'stroke_width': 0.1, 'stroke_color': 0.01}, 'lr_schedule': False, 'num_paths': 512, 'max_width': 5.0, 'path_type': 'unclosed', 'loss_type': 'l2'}

***** Model State *****
-> Mixed Precision: no, AMP: False
-> Weight dtype:  torch.float32
-> Working Space: '/home/lyxy232/lyxy/PyTorch-SVGRender/workspace/diffvg-2025-01-18-00-03/sd951222-unclosed-P512'
Process 0 using device: cuda
-> state initialization complete 

load image from: 'data/fallingwater.png'
init_image shape:  torch.Size([1, 3, 512, 341])
/home/lyxy232/miniconda3/envs/svgrender/lib/python3.10/site-packages/torch/_compile.py:32: UserWarning: optimizer contains a parameter group with duplicate parameters; in future, this will cause an error; see github.com/pytorch/pytorch/issues/40967 for more information
  return disable_fn(*args, **kwargs)
lr: 1.0000, L_recon: 0.0101:   7%|██████▍                                                                                 | 145/2000 [01:49<23:56,  1.29it/s]Exception ignored in: <function Image.__del__ at 0x70a72fd4a950>
Traceback (most recent call last):
  File "/home/lyxy232/miniconda3/envs/svgrender/lib/python3.10/tkinter/__init__.py", line 4056, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x70a7307c31c0>
Traceback (most recent call last):
  File "/home/lyxy232/miniconda3/envs/svgrender/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x70a7307c31c0>
Traceback (most recent call last):
  File "/home/lyxy232/miniconda3/envs/svgrender/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x70a7307c31c0>
Traceback (most recent call last):
  File "/home/lyxy232/miniconda3/envs/svgrender/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x70a7307c31c0>
Traceback (most recent call last):
  File "/home/lyxy232/miniconda3/envs/svgrender/lib/python3.10/tkinter/__init__.py", line 388, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Tcl_AsyncDelete: async handler deleted by the wrong thread
已中止 (核心已转储)
`
